#############################################################################
# Makefile for building: Y-SPICE
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  main.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile main.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Y-SPICE1.0.0
DISTDIR = /home/kyon/eda_course/assignment4/hw4_project/build/Y-SPICE1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -larmadillo -llapack -lblas -lfl -ly /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/analyser/analyser.cpp \
		src/circuit/circuit.cpp \
		src/devices/capacitor.cpp \
		src/devices/cccs.cpp \
		src/devices/ccvs.cpp \
		src/devices/cs.cpp \
		src/devices/device.cpp \
		src/devices/inductor.cpp \
		src/devices/resistor.cpp \
		src/devices/vccs.cpp \
		src/devices/vcvs.cpp \
		src/devices/vs.cpp \
		src/mainwindow/mainwindow.cpp \
		src/parser/parser.cpp \
		src/parser/scanner.cpp \
		src/simulator_interface/simulator_interface.cpp \
		src/result_recorder/result_recorder.cpp \
		src/plotter/plotter.cpp \
		src/plotter/qcustomplot/qcustomplot.cpp \
		src/function_generator/pulse.cpp \
		src/function_generator/sin.cpp \
		src/spice-log/log.cpp build/qrc_mainwindow.cpp \
		build/moc_mainwindow.cpp \
		build/moc_qcustomplot.cpp
OBJECTS       = build/main.o \
		build/analyser.o \
		build/circuit.o \
		build/capacitor.o \
		build/cccs.o \
		build/ccvs.o \
		build/cs.o \
		build/device.o \
		build/inductor.o \
		build/resistor.o \
		build/vccs.o \
		build/vcvs.o \
		build/vs.o \
		build/mainwindow.o \
		build/parser.o \
		build/scanner.o \
		build/simulator_interface.o \
		build/result_recorder.o \
		build/plotter.o \
		build/qcustomplot.o \
		build/pulse.o \
		build/sin.o \
		build/log.o \
		build/qrc_mainwindow.o \
		build/moc_mainwindow.o \
		build/moc_qcustomplot.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		main.pro src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/circuit/node.h \
		src/devices/device.h \
		src/mainwindow/mainwindow.h \
		src/parser/parser.hpp \
		src/parser/scanner.hpp \
		src/simulator_interface/simulator_interface.h \
		src/spice_command/command_plot.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/result_recorder/result_recorder.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/plotter/plotter.h \
		src/function_generator/function_generator.h \
		src/spice-log/log.h src/main.cpp \
		src/analyser/analyser.cpp \
		src/circuit/circuit.cpp \
		src/devices/capacitor.cpp \
		src/devices/cccs.cpp \
		src/devices/ccvs.cpp \
		src/devices/cs.cpp \
		src/devices/device.cpp \
		src/devices/inductor.cpp \
		src/devices/resistor.cpp \
		src/devices/vccs.cpp \
		src/devices/vcvs.cpp \
		src/devices/vs.cpp \
		src/mainwindow/mainwindow.cpp \
		src/parser/parser.cpp \
		src/parser/scanner.cpp \
		src/simulator_interface/simulator_interface.cpp \
		src/result_recorder/result_recorder.cpp \
		src/plotter/plotter.cpp \
		src/plotter/qcustomplot/qcustomplot.cpp \
		src/function_generator/pulse.cpp \
		src/function_generator/sin.cpp \
		src/spice-log/log.cpp
QMAKE_TARGET  = Y-SPICE
DESTDIR       = 
TARGET        = Y-SPICE


first: all
####### Build rules

Y-SPICE: flexBison $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: main.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		main.pro \
		src/mainwindow/mainwindow.qrc
	$(QMAKE) -o Makefile main.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
main.pro:
src/mainwindow/mainwindow.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile main.pro

qmake_all: FORCE


all: Makefile Y-SPICE

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow/mainwindow.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/analyser/analyser.h src/circuit/circuit.h src/circuit/node.h src/devices/device.h src/mainwindow/mainwindow.h src/parser/parser.hpp src/parser/scanner.hpp src/simulator_interface/simulator_interface.h src/spice_command/command_plot.h src/spice_command/command_ac.h src/spice_command/command_dc.h src/spice_command/command_tran.h src/result_recorder/result_recorder.h src/plotter/qcustomplot/qcustomplot.h src/plotter/plotter.h src/function_generator/function_generator.h src/spice-log/log.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/analyser/analyser.cpp src/circuit/circuit.cpp src/devices/capacitor.cpp src/devices/cccs.cpp src/devices/ccvs.cpp src/devices/cs.cpp src/devices/device.cpp src/devices/inductor.cpp src/devices/resistor.cpp src/devices/vccs.cpp src/devices/vcvs.cpp src/devices/vs.cpp src/mainwindow/mainwindow.cpp src/parser/parser.cpp src/parser/scanner.cpp src/simulator_interface/simulator_interface.cpp src/result_recorder/result_recorder.cpp src/plotter/plotter.cpp src/plotter/qcustomplot/qcustomplot.cpp src/function_generator/pulse.cpp src/function_generator/sin.cpp src/spice-log/log.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) ./src/parser/parser.cpp ./src/parser/parser.hpp ./src/parser/scanner.cpp ./src/parser/scanner.hpp
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

linecount: FORCE
	find . -type f \( -name "*.cpp" -o -name "*.lex" -o -name "*.yy" -o -name "*.h" \) ! -name "qcustomplot.cpp" ! -name "qcustomplot.h" ! -name "parser.cpp" ! -name "parser.hpp" ! -name "scanner.cpp" ! -name "scanner.hpp" ! -name "moc_*.*" ! -name "qrc_*.*" -print0 | xargs -0 wc -l

flexBison: FORCE
	make -C ./src/parser flex_bison_output

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/qrc_mainwindow.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/qrc_mainwindow.cpp
build/qrc_mainwindow.cpp: src/mainwindow/mainwindow.qrc \
		/usr/lib/qt5/bin/rcc \
		asset/images/filesave.png \
		asset/images/filesaveall.png \
		asset/images/fileopen.png \
		asset/images/filenew.png \
		asset/images/simulate.png \
		asset/images/editcut.png \
		asset/images/editdelete.png \
		asset/images/editpaste.png \
		asset/images/filesaveas.png \
		asset/images/editcopy.png \
		asset/images/fileclose.png \
		asset/images/fileprint.png
	/usr/lib/qt5/bin/rcc -name mainwindow src/mainwindow/mainwindow.qrc -o build/qrc_mainwindow.cpp

compiler_moc_predefs_make_all: build/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc_predefs.h
build/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -Wextra -dM -E -o build/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc_mainwindow.cpp build/moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mainwindow.cpp build/moc_qcustomplot.cpp
build/moc_mainwindow.cpp: src/mainwindow/mainwindow.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kyon/eda_course/assignment4/hw4_project/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kyon/eda_course/assignment4/hw4_project -I/home/kyon/eda_course/assignment4/hw4_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow/mainwindow.h -o build/moc_mainwindow.cpp

build/moc_qcustomplot.cpp: src/plotter/qcustomplot/qcustomplot.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kyon/eda_course/assignment4/hw4_project/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kyon/eda_course/assignment4/hw4_project -I/home/kyon/eda_course/assignment4/hw4_project/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/plotter/qcustomplot/qcustomplot.h -o build/moc_qcustomplot.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/main.o: src/main.cpp src/mainwindow/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/analyser.o: src/analyser/analyser.cpp src/analyser/analyser.h \
		src/devices/device.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/analyser.o src/analyser/analyser.cpp

build/circuit.o: src/circuit/circuit.cpp src/circuit/circuit.h \
		src/analyser/analyser.h \
		src/devices/device.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/circuit.o src/circuit/circuit.cpp

build/capacitor.o: src/devices/capacitor.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/capacitor.o src/devices/capacitor.cpp

build/cccs.o: src/devices/cccs.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/cccs.o src/devices/cccs.cpp

build/ccvs.o: src/devices/ccvs.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ccvs.o src/devices/ccvs.cpp

build/cs.o: src/devices/cs.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/cs.o src/devices/cs.cpp

build/device.o: src/devices/device.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/device.o src/devices/device.cpp

build/inductor.o: src/devices/inductor.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/inductor.o src/devices/inductor.cpp

build/resistor.o: src/devices/resistor.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/resistor.o src/devices/resistor.cpp

build/vccs.o: src/devices/vccs.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/vccs.o src/devices/vccs.cpp

build/vcvs.o: src/devices/vcvs.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/vcvs.o src/devices/vcvs.cpp

build/vs.o: src/devices/vs.cpp src/devices/device.h \
		src/analyser/analyser.h \
		src/circuit/circuit.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/vs.o src/devices/vs.cpp

build/mainwindow.o: src/mainwindow/mainwindow.cpp src/mainwindow/mainwindow.h \
		src/simulator_interface/simulator_interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindow.o src/mainwindow/mainwindow.cpp

build/parser.o: src/parser/parser.cpp src/parser/parser.hpp \
		src/circuit/circuit.h \
		src/analyser/analyser.h \
		src/devices/device.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/parser.o src/parser/parser.cpp

build/scanner.o: src/parser/scanner.cpp src/parser/parser.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/scanner.o src/parser/scanner.cpp

build/simulator_interface.o: src/simulator_interface/simulator_interface.cpp src/parser/parser.hpp \
		src/circuit/circuit.h \
		src/analyser/analyser.h \
		src/devices/device.h \
		src/circuit/node.h \
		src/function_generator/function_generator.h \
		src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h \
		src/spice_command/command.h \
		src/spice_command/command_ac.h \
		src/spice_command/command_dc.h \
		src/spice_command/command_tran.h \
		src/spice_command/command_plot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/simulator_interface.o src/simulator_interface/simulator_interface.cpp

build/result_recorder.o: src/result_recorder/result_recorder.cpp src/result_recorder/result_recorder.h \
		src/plotter/plotter.h \
		src/plotter/qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/result_recorder.o src/result_recorder/result_recorder.cpp

build/plotter.o: src/plotter/plotter.cpp src/plotter/qcustomplot/qcustomplot.h \
		src/plotter/plotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/plotter.o src/plotter/plotter.cpp

build/qcustomplot.o: src/plotter/qcustomplot/qcustomplot.cpp src/plotter/qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qcustomplot.o src/plotter/qcustomplot/qcustomplot.cpp

build/pulse.o: src/function_generator/pulse.cpp src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/pulse.o src/function_generator/pulse.cpp

build/sin.o: src/function_generator/sin.cpp src/function_generator/function_generator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/sin.o src/function_generator/sin.cpp

build/log.o: src/spice-log/log.cpp src/spice-log/log.h \
		src/mainwindow/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/log.o src/spice-log/log.cpp

build/qrc_mainwindow.o: build/qrc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_mainwindow.o build/qrc_mainwindow.cpp

build/moc_mainwindow.o: build/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindow.o build/moc_mainwindow.cpp

build/moc_qcustomplot.o: build/moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_qcustomplot.o build/moc_qcustomplot.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

